# Site Settings
title: Arden Wolfsky's Speakeasy
tagline: Cheers, Awoo!
baseurl: ""
url: "http://localhost:5000"
permalink: "/drinks/:slug"

paginate: 9
paginate_path: "/page:num"

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      show_sidebar: true
      border: true

collections:
  tags:
    output: true
    permalink: /tag/:name

exclude:
  - build.*
  - LICENSE.txt
  - mere-blog-theme.gemspec
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - scripts/