# Site Settings
title: Arden Wolfsky's Speakeasy
tagline: Cheers, Awoo!
url: "https://ardenwolfsky.com"
permalink: "/drinks/:slug"

pagination:
  enabled: true
  per_page: 9
  permalink: '/page:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  collection: 'posts'

# Image CDN root
cdn: "https://ardenwolfsky.com/cdn-cgi/imagedelivery/GWpL3YoIe0wj5_zHZfF0dA/"

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2
  - jekyll-feed
  - jekyll-seo-tag

livereload: true

sass:
  style: compressed
  source_dir: _sass

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      border: true

exclude:
  - build.*
  - LICENSE.txt
  - mere-blog-theme.gemspec
  - package.json
  - package-lock.json
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - scripts/
  - ardenwolfsky-theme.gemspec